name 'dhoppe-collectd'
version '0.1.0'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-collectd'
source 'git://github.com/dhoppe/puppet-collectd'
summary 'Collectd Module'
description 'Collectd Module for Debian, Ubuntu'
dependency 'puppetlabs/stdlib', '>=0.0.1'
